// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtP1Db4KNwyKdkUPFx4Yf0gR5Tz_h8Yuw',
    appId: '1:977046512595:web:ee4bff6b087ea12f9d4526',
    messagingSenderId: '977046512595',
    projectId: 'arshopapp-65560',
    authDomain: 'arshopapp-65560.firebaseapp.com',
    storageBucket: 'arshopapp-65560.firebasestorage.app',
    measurementId: 'G-52M659TJM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj3hV7fnLPQIlTywOppPCSd1RqbO6HRzw',
    appId: '1:977046512595:android:5757b8ae0de167649d4526',
    messagingSenderId: '977046512595',
    projectId: 'arshopapp-65560',
    storageBucket: 'arshopapp-65560.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoQtuUdrNIIFAQZiE6bRHWW5qiJyNQCtQ',
    appId: '1:977046512595:ios:06332bf8a806e5879d4526',
    messagingSenderId: '977046512595',
    projectId: 'arshopapp-65560',
    storageBucket: 'arshopapp-65560.firebasestorage.app',
    androidClientId: '977046512595-efb8vmm46v4pe764r83k4hmjguu47ln1.apps.googleusercontent.com',
    iosClientId: '977046512595-urich16p6l0rarsvi62re9eh5s5uup5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.arshopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoQtuUdrNIIFAQZiE6bRHWW5qiJyNQCtQ',
    appId: '1:977046512595:ios:06332bf8a806e5879d4526',
    messagingSenderId: '977046512595',
    projectId: 'arshopapp-65560',
    storageBucket: 'arshopapp-65560.firebasestorage.app',
    androidClientId: '977046512595-efb8vmm46v4pe764r83k4hmjguu47ln1.apps.googleusercontent.com',
    iosClientId: '977046512595-urich16p6l0rarsvi62re9eh5s5uup5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.arshopapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtP1Db4KNwyKdkUPFx4Yf0gR5Tz_h8Yuw',
    appId: '1:977046512595:web:b81a7d1fdb04df169d4526',
    messagingSenderId: '977046512595',
    projectId: 'arshopapp-65560',
    authDomain: 'arshopapp-65560.firebaseapp.com',
    storageBucket: 'arshopapp-65560.firebasestorage.app',
    measurementId: 'G-QJJQHHC6HY',
  );

}