// lib/main.dart

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';

import 'core/router.dart';
import 'core/theme.dart';
import 'repositories/auth_repository.dart';
import 'viewmodels/auth_viewmodel.dart';

// Generated by: flutterfire configure
// import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    // options: DefaultFirebaseOptions.currentPlatform, // uncomment after flutterfire configure
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // Register the repository as a singleton
        Provider<AuthRepository>(
          create: (_) => AuthRepository(),
        ),

        // Register the ViewModel — injects the repository
        ChangeNotifierProxyProvider<AuthRepository, AuthViewModel>(
          create: (context) =>
              AuthViewModel(context.read<AuthRepository>()),
          update: (context, repo, previous) =>
          previous ?? AuthViewModel(repo),
        ),
      ],
      child: MaterialApp(
        title: 'AR Home Decor',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.lightTheme,
        initialRoute: AppRouter.splash,
        routes: AppRouter.routes,
      ),
    );
  }
}